import localFont from "next/font/local";
import "./globals.css";
import CardActivation from "@/components/CardActivation";
import {Inter} from "@next/font/google";
import Header from "@/components/Header";



const inter = Inter({
  weight:'400',
  subsets:['cyrillic'],
});


export const metadata = {
  title: "User Guidance",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} text-l  m-10` }>
        <Header />
        <CardActivation />
        {children}
      </body>
    </html>
  );
}
